name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    name: build extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "ci"
          cache-directories: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/

      - name: install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: "1.81"
          target: "wasm32-wasip1"

      - name: build wasm
        run: cargo build --target wasm32-wasip1
